INSERT INTO todo (title, content, user_id) VALUES ('sample1', 'sometask lorem ipsum', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample2', 'sometask 업드리라고 ', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample3', 'sometask 누군가 가고있어 조심해', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample4', '지방검사 보가 위험함.', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample5', '다음 주에 다시해야해. 다행이네요. 아니, 안돼요. 개인분장팀이야', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample6', '암살자가 쫏아가고 있어서 숨어야함', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample7', 'copy room', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample8', '경찰이다. 무기버려라', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample9', '안전하니 나와도되 ㅇ난 술한자해야 겠어...', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample10', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample11', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample12', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample13', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample14', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample15', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample16', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample17', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample18', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample19', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample20', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample21', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample22', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample23', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample24', 'sometask', 2);
INSERT INTO todo (title, content, user_id) VALUES ('sample25', 'sometask', 2);